### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by stepanje** [kvuong2711/OpenTrafficCam3D#2]
Hello,

Thank you for sharing this project!

I would like to ask about the license of the source code? Would it be possible to add a license to the repository?

Thank you.

**Comment by kvuong2711** [comment]
Hello @stepanje,

 I added the MIT License. However, there are 2 things:

1) The access and usage of streetview data should follow their own license

2) If you used the reconstruction and/or localization code, they have some dependencies which are separately licensed, e.g., https://github.com/magicleap/SuperPointPretrainedNetwork/blob/master/LICENSE

**Comment by stepanje** [comment]
Thank you!
