### ISSUE TITLE
Regarding Camera POV

### ISSUE THREAD

**Issue by karanpandyaa** [kvuong2711/OpenTrafficCam3D#3]
Hi @kvuong2711, In the video on the project page, you have showed the reconstruction from the estimated camera pov and then compared it with the query image. 

Can you elaborate how did you do that? I am not able to see the scene from the reconstructed camera pov in colmap.

Also, can we connect on LinkedIn, need a bit of you assistance. https://www.linkedin.com/in/karan-pandya2 .

**Comment by kvuong2711** [comment]
Hi @karanpandyaa,

I rendered the image of the point cloud using the query camera's (estimated) intrinsics & extrinsics with Open3D. See more info here: https://github.com/isl-org/Open3D/issues/1483.

I'm afraid I cannnot help with the specific use case of your project, but feel free to raise any question here if it's related to this repo!
